package it.polimi.ingsw.common;

/**
 * Enum of every type of exchanged messages
 */
public enum MessageType {
    NICKNAME_REPLY,
    DISCARD_INITIAL_LEADER,
    CHOOSE_INITIAL_RESOURCES,
    ERROR,
    CREATE_MATCH_REPLY,
    TAKE_FROM_MARKET,
    TRANSFORM_WHITE_MARBLES,
    TRANSFORM_MARBLES,
    MARKET_UPDATE,
    CARD_GRID_UPDATE,
    INITIAL_LEADER_DISCARDED_UPDATE,
    TEMPORARY_RESOURCE_MAP_UPDATE,
    TEMPORARY_MARBLES_UPDATE,
    ADD_TO_WAREHOUSE,
    WAREHOUSE_UPDATE,
    INITIAL_LEADERCARDS_UPDATE,
    PLAYER_TURN_UPDATE,
    ACTIVATE_LEADER,
    LEADERCARD_ACTIVATED_UPDATE,
    ADD_SPECIALDEPOT_UPDATE
}
